---
name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version
      - name: Install dependencies
        run: pip install pandas numpy requests
      - name: MegaLinter
        run: ./scripts/lint -c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
